version: "3.8"

services:
    fin_api_db:
        image: postgres
        container_name: fin_api_db
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=ignite
            - POSTGRES_DB=fin_api
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: finApi
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - fin_api_db
        depends_on:
            - fin_api_db

volumes:
    pgdata:
        driver: local
